using System.Globalization;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Stikling.Core.Care;
using Stikling.Core.Feeds;
using Stikling.Core.Names;
using Stikling.Core.Pests;
using Stikling.Core.Plants;
using Stikling.Core.Pots;
using Stikling.Core.Products;
using Stikling.Core.SoilMixes;
using Stikling.Core.Propagations;
using Stikling.Core.Rooms;
using Stikling.Core.Settings;
using Stikling.Core.Timeline;
using Stikling.Core.Today;
using Stikling.Web;
using Stikling.Web.Services;

// The app is in English, so dates read "19 Sep 2026" regardless of the browser's language
var culture = new CultureInfo("en-GB");
CultureInfo.DefaultThreadCurrentCulture = culture;
CultureInfo.DefaultThreadCurrentUICulture = culture;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

builder.Services.AddSingleton(TimeProvider.System);
builder.Services.AddScoped(_ => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
builder.Services.AddScoped<ThemeService>();
builder.Services.AddScoped<IndexedDb>();
builder.Services.AddScoped<IPlantRepository, IndexedDbPlantRepository>();
builder.Services.AddScoped<IPropagationRepository, IndexedDbPropagationRepository>();
builder.Services.AddScoped<ICareLogRepository, IndexedDbCareLogRepository>();
builder.Services.AddScoped<IPestCaseRepository, IndexedDbPestCaseRepository>();
builder.Services.AddScoped<IPestTreatmentRepository, IndexedDbPestTreatmentRepository>();
builder.Services.AddScoped<ITreatmentRecipeRepository, IndexedDbTreatmentRecipeRepository>();
builder.Services.AddScoped<IPotRepository, IndexedDbPotRepository>();
builder.Services.AddScoped<IPlaceRepository, IndexedDbPlaceRepository>();
builder.Services.AddScoped<ISoilMixRepository, IndexedDbSoilMixRepository>();
builder.Services.AddScoped<IProductRepository, IndexedDbProductRepository>();
builder.Services.AddScoped<IFeedRepository, IndexedDbFeedRepository>();
builder.Services.AddScoped<ISettingsRepository, IndexedDbSettingsRepository>();
builder.Services.AddScoped<IPutOffRepository, IndexedDbPutOffRepository>();
builder.Services.AddScoped<ITimelineRepository, IndexedDbTimelineRepository>();
builder.Services.AddScoped<IPhotoRepository, IndexedDbPhotoRepository>();
builder.Services.AddScoped<IPlantNameSource, BundledPlantNames>();
builder.Services.AddScoped<TimelineService>();
builder.Services.AddScoped<PlantService>();
builder.Services.AddScoped<PropagationService>();
builder.Services.AddScoped<PlantNameService>();
builder.Services.AddScoped<RoomService>();
builder.Services.AddScoped<PotService>();
builder.Services.AddScoped<SoilMixService>();
builder.Services.AddScoped<ProductService>();
builder.Services.AddScoped<FeedService>();
builder.Services.AddScoped<SettingsService>();
builder.Services.AddScoped<PutOffService>();
builder.Services.AddScoped<CareService>();
builder.Services.AddScoped<PhotoService>();
builder.Services.AddScoped<DeviceFiles>();
builder.Services.AddScoped<AppBadge>();
builder.Services.AddScoped<BackupService>();

await builder.Build().RunAsync();
